### ISSUE TITLE
Do the distribution async would be more performed. 

### ISSUE THREAD

**Issue by nimatrengo** [rleroi/webhook-nemesis#1]
Awesome library, it seems so easy and practical. 

As a remark, I believe that the process would be "Async" instead of "Sync", imagine that one of the URLs gave a timeout, in terms of the issue we need to wait for the response to trigger the next link. would be better to make it Async and for this subject, we have to change "Foreach" to "for" as it does not support the "Async" process. 
https://codeburst.io/javascript-async-await-with-foreach-b6ba62bbf404

https://github.com/rleroi/webhook-nemesis/blob/83ad50dc3828e1d2484bb233f97f3a13d85d6748/distribute.js#L11-L26

**Comment by rleroi** [comment]
Why would you want to wait before triggering the next request? It is faster to call them all at the same time asynchronously.

**Comment by nimatrengo** [comment]
Aw, my mistake, you are doing it Async in line 24, that is what I meant. fair enough.
